import { GoogleGenAI, Type } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        { error: "NO_API_KEY", message: "GEMINI_API_KEY is not configured." },
        { status: 400 }
      );
    }

    const { topic: rawTopic, difficulty = 'media', trackId: rawTrackId = 'python', language: rawLang = 'it' } = await req.json();

    const topic = typeof rawTopic === 'string' ? rawTopic.slice(0, 100) : 'General';
    const trackId = typeof rawTrackId === 'string' ? rawTrackId.slice(0, 30) : 'python';
    const language = typeof rawLang === 'string' ? rawLang.slice(0, 5) : 'it';

    const ai = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });

    const prompt = `Generate a new programming challenge for the "${trackId}" track on topic "${topic}" with difficulty "${difficulty}".
Requested language for text and explanation: ${language === 'it' ? 'Italian' : language === 'es' ? 'Spanish' : 'English'}.

The challenge must contain:
- A representative source code snippet with a bug or specific behavior.
- A clear question about the output, bug, or correct solution.
- 4 distinct answer options.
- The correct answer index (0-3).
- A detailed and instructive explanation.
- A progressive hint.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are an educational programming challenge generator. Output strict JSON for DevQuest.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            domanda: { type: Type.STRING, description: "Question text" },
            codice: { type: Type.STRING, description: "Code snippet with syntax highlighting" },
            risposte: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Array of exactly 4 answer options"
            },
            rispostaCorretta: { type: Type.INTEGER, description: "Index 0-3 of the correct answer" },
            spiegazione: { type: Type.STRING, description: "Detailed educational explanation" },
            suggerimento: { type: Type.STRING, description: "Hint to guide the student" },
            argomento: { type: Type.STRING, description: "Specific topic name" }
          },
          required: ["domanda", "codice", "risposte", "rispostaCorretta", "spiegazione", "suggerimento", "argomento"]
        }
      }
    });

    if (!response.text) {
      throw new Error("No response generated by Gemini");
    }

    const questData = JSON.parse(response.text);

    // Format into Sfida type
    const newSfida = {
      id: `ai_gen_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      capitolo: 99,
      argomento: questData.argomento || topic,
      domanda: questData.domanda,
      codice: questData.codice,
      risposte: questData.risposte,
      indice_corretto: Number(questData.rispostaCorretta),
      spiegazione: questData.spiegazione,
      suggerimento: questData.suggerimento,
      difficolta: difficulty === 'facile' ? 'facile' : difficulty === 'difficile' ? 'difficile' : 'media',
      trackId: trackId,
      isCustom: true,
      author: 'AI Quest Engine'
    };

    return NextResponse.json({ quest: newSfida });
  } catch (error: unknown) {
    console.error("Error generating quest:", error);
    const msg = error instanceof Error ? error.message : "Generic error";
    return NextResponse.json({ error: "GENERATION_FAILED", message: msg }, { status: 500 });
  }
}
