import { Challenge } from './types';

export const DOCKER_CHALLENGES: Challenge[] = [
  {
    id: 'docker-1-1',
    trackId: 'docker',
    chapter: 1,
    topic: 'Container Basics',
    difficulty: 'easy',
    question: 'Quale comando Docker elenca tutti i container attualmente in esecuzione sul sistema?',
    question_en: 'Which Docker command lists all currently running containers on the system?',
    question_es: '¿Qué comando de Docker enumera todos los contenedores en ejecución?',
    code: 'docker _______',
    options: ['ps', 'list', 'show', 'containers'],
    correctIndex: 0,
    hint: 'Si tratta del comando analogo al comando Unix per i processi.',
    hint_en: 'It is analogous to the Unix command for listing processes.',
    explanation: '`docker ps` mostra la lista dei container attivi. Usando `docker ps -a` si vedono anche quelli arrestati.',
    explanation_en: '`docker ps` lists active containers. Adding `-a` shows stopped ones too.'
  },
  {
    id: 'docker-1-2',
    trackId: 'docker',
    chapter: 1,
    topic: 'Container Execution',
    difficulty: 'easy',
    question: 'Come si avvia un container in modalità "detached" (in background)?',
    question_en: 'How do you run a container in detached mode (background)?',
    question_es: '¿Cómo se ejecuta un contenedor en modo "detached" (en segundo plano)?',
    code: 'docker run -___ nginx',
    options: ['d', 'b', 'bg', 'detach'],
    correctIndex: 0,
    hint: 'La lettera iniziale della parola "detached".',
    hint_en: 'The first letter of the word "detached".',
    explanation: 'Il flag `-d` (o `--detach`) esegue il container in background e stampa l\'ID del container.',
    explanation_en: 'The `-d` flag (short for `--detach`) runs the container in background.'
  },
  {
    id: 'docker-2-1',
    trackId: 'docker',
    chapter: 2,
    topic: 'Dockerfile Directives',
    difficulty: 'medium',
    question: 'Nel Dockerfile, quale direttiva specifica l\'immagine di partenza (base image)?',
    question_en: 'In a Dockerfile, which directive specifies the base image?',
    question_es: 'En un Dockerfile, ¿qué directiva especifica la imagen base?',
    code: '_______ python:3.11-slim\nWORKDIR /app\nCOPY . .',
    options: ['FROM', 'BASE', 'ROOT', 'IMAGE'],
    correctIndex: 0,
    hint: 'Ogni Dockerfile valido inizia quasi sempre con questa istruzione.',
    hint_en: 'Almost every valid Dockerfile starts with this keyword.',
    explanation: '`FROM` imposta l\'immagine base su cui verranno applicate tutte le istruzioni successive.',
    explanation_en: '`FROM` sets the base image for subsequent instructions.'
  },
  {
    id: 'docker-2-2',
    trackId: 'docker',
    chapter: 2,
    topic: 'Port Mapping',
    difficulty: 'medium',
    question: 'Come si mppa la porta 8080 dell\'host alla porta 80 del container?',
    question_en: 'How do you map host port 8080 to container port 80?',
    question_es: '¿Cómo se mapea el puerto 8080 del host al puerto 80 del contenedor?',
    code: 'docker run -p _______ nginx',
    options: ['8080:80', '80:8080', '8080->80', '8080=80'],
    correctIndex: 0,
    hint: 'La sintassi della porta è sempre host_port:container_port.',
    hint_en: 'Port syntax is always host_port:container_port.',
    explanation: 'La sintassi `-p host_port:container_port` inoltra il traffico dalla macchina host dentro al container.',
    explanation_en: 'The `-p host:container` flag maps incoming host traffic into the container.'
  },
  {
    id: 'docker-3-1',
    trackId: 'docker',
    chapter: 3,
    topic: 'Docker Compose',
    difficulty: 'hard',
    question: 'Quale comando avvia tutti i servizi definiti nel file `docker-compose.yml`?',
    question_en: 'Which command starts all services defined in a `docker-compose.yml` file?',
    question_es: '¿Qué comando inicia todos los servicios definidos en `docker-compose.yml`?',
    code: 'docker compose _______ -d',
    options: ['up', 'start', 'run', 'launch'],
    correctIndex: 0,
    hint: 'Il contrario di "down".',
    hint_en: 'The opposite of "down".',
    explanation: '`docker compose up` crea e avvia i container, le reti e i volumi definiti nel file compose.',
    explanation_en: '`docker compose up` builds, creates, and starts all multi-container services.'
  }
];
