import { Sfida, TrackId, normalizeChallenge } from './types';
import { INITIAL_TYPESCRIPT_CHALLENGES, INITIAL_GIT_CHALLENGES } from './content/initial_challenges';
import { DOCKER_CHALLENGES } from './challenges_docker';
import { POSTGRES_CHALLENGES } from './challenges_postgres';
import { AI_NATIVE_CHALLENGES } from './challenges_ai';

export const SFIDE_PYTHON: Sfida[] = [
  // --- BASI (Capitoli 1-2) ---

  {
    id: "bas-01",
    capitolo: 1,
    argomento: "Print",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print('Ciao')",
    risposte: ["Ciao", "'Ciao'", "Niente", "Error"],
    indice_corretto: 0,
    suggerimento: "print mostra il testo a schermo senza le virgolette.",
    spiegazione: "La funzione print() stampa la stringa 'Ciao' senza gli apici.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Ciao", "'Ciao'", "Nothing", "Error"],
    risposte_es: ["Ciao", "'Ciao'", "Nada", "Error"],
    suggerimento_en: "print displays text on the screen without the quotes.",
    suggerimento_es: "print muestra el texto en pantalla sin las comillas.",
    spiegazione_en: "The print() function prints the string 'Ciao' without the quotes.",
    spiegazione_es: "La función print() imprime la cadena 'Ciao' sin las comillas.",
  },
  {
    id: "bas-02",
    capitolo: 1,
    argomento: "Type int",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(type(5))",
    risposte: ["<class 'int'>", "<class 'float'>", "5", "Error"],
    indice_corretto: 0,
    suggerimento: "5 è un numero intero.",
    spiegazione: "type(5) restituisce la classe int degli interi.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["<class 'int'>", "<class 'float'>", "5", "Error"],
    risposte_es: ["<class 'int'>", "<class 'float'>", "5", "Error"],
    suggerimento_en: "5 is an integer.",
    suggerimento_es: "5 es un número entero.",
    spiegazione_en: "type(5) returns the int class for integers.",
    spiegazione_es: "type(5) devuelve la clase int de los enteros.",
  },
  {
    id: "bas-03",
    capitolo: 1,
    argomento: "Type float",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(type(2.5))",
    risposte: ["<class 'float'>", "<class 'int'>", "2.5", "Error"],
    indice_corretto: 0,
    suggerimento: "2.5 è un numero decimale.",
    spiegazione: "I numeri decimali in Python appartengono alla classe float.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["<class 'float'>", "<class 'int'>", "2.5", "Error"],
    risposte_es: ["<class 'float'>", "<class 'int'>", "2.5", "Error"],
    suggerimento_en: "2.5 is a decimal number.",
    suggerimento_es: "2.5 es un número decimal.",
    spiegazione_en: "Decimal numbers in Python belong to the float class.",
    spiegazione_es: "Los números decimales en Python pertenecen a la clase float.",
  },
  {
    id: "bas-04",
    capitolo: 1,
    argomento: "Type str",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(type('hi'))",
    risposte: ["<class 'str'>", "<class 'int'>", "hi", "Error"],
    indice_corretto: 0,
    suggerimento: "I testi racchiusi da apici sono stringhe.",
    spiegazione: "Tra apici è un oggetto della classe str.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["<class 'str'>", "<class 'int'>", "hi", "Error"],
    risposte_es: ["<class 'str'>", "<class 'int'>", "hi", "Error"],
    suggerimento_en: "Text enclosed in quotes are strings.",
    suggerimento_es: "Los textos encerrados entre comillas son cadenas (strings).",
    spiegazione_en: "Anything between quotes is an object of the str class.",
    spiegazione_es: "Entre comillas es un objeto de la clase str.",
  },
  {
    id: "bas-05",
    capitolo: 2,
    argomento: "Variabile",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "x = 5\nprint(x)",
    risposte: ["5", "x", "Error", "Niente"],
    indice_corretto: 0,
    suggerimento: "x contiene il valore 5.",
    spiegazione: "print(x) valuta la variabile x e ne stampa il valore 5.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["5", "x", "Error", "Nothing"],
    risposte_es: ["5", "x", "Error", "Nada"],
    suggerimento_en: "x contains the value 5.",
    suggerimento_es: "x contiene el valor 5.",
    spiegazione_en: "print(x) evaluates the variable x and prints its value 5.",
    spiegazione_es: "print(x) evalúa la variable x e imprime su valor 5.",
  },
  {
    id: "bas-06",
    capitolo: 2,
    argomento: "Addizione",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(2 + 3)",
    risposte: ["5", "23", "Error", "Niente"],
    indice_corretto: 0,
    suggerimento: "L'operatore + esegue la somma algebrica.",
    spiegazione: "2 + 3 equivale a 5.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["5", "23", "Error", "Nothing"],
    risposte_es: ["5", "23", "Error", "Nada"],
    suggerimento_en: "The + operator performs algebraic addition.",
    suggerimento_es: "El operador + realiza la suma algebraica.",
    spiegazione_en: "2 + 3 equals 5.",
    spiegazione_es: "2 + 3 equivale a 5.",
  },
  {
    id: "bas-07",
    capitolo: 2,
    argomento: "Sottrazione",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(10 - 4)",
    risposte: ["6", "14", "-6", "Error"],
    indice_corretto: 0,
    suggerimento: "L'operatore - sottrae il secondo numero dal primo.",
    spiegazione: "10 - 4 = 6.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["6", "14", "-6", "Error"],
    risposte_es: ["6", "14", "-6", "Error"],
    suggerimento_en: "The - operator subtracts the second number from the first.",
    suggerimento_es: "El operador - resta el segundo número del primero.",
    spiegazione_en: "10 - 4 = 6.",
    spiegazione_es: "10 - 4 = 6.",
  },
  {
    id: "bas-08",
    capitolo: 2,
    argomento: "Moltiplicazione",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(3 * 4)",
    risposte: ["12", "7", "34", "Error"],
    indice_corretto: 0,
    suggerimento: "* è l'operatore di moltiplicazione.",
    spiegazione: "3 * 4 = 12.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["12", "7", "34", "Error"],
    risposte_es: ["12", "7", "34", "Error"],
    suggerimento_en: "* is the multiplication operator.",
    suggerimento_es: "* es el operador de multiplicación.",
    spiegazione_en: "3 * 4 = 12.",
    spiegazione_es: "3 * 4 = 12.",
  },
  {
    id: "bas-09",
    capitolo: 2,
    argomento: "Divisione",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(10 / 2)",
    risposte: ["5.0", "5", "2.5", "Error"],
    indice_corretto: 0,
    suggerimento: "La divisione / in Python 3 restituisce sempre un float.",
    spiegazione: "10 / 2 calcola la divisione floating point e restituisce 5.0.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["5.0", "5", "2.5", "Error"],
    risposte_es: ["5.0", "5", "2.5", "Error"],
    suggerimento_en: "The / division operator in Python 3 always returns a float.",
    suggerimento_es: "La división / en Python 3 siempre devuelve un float.",
    spiegazione_en: "10 / 2 performs floating point division and returns 5.0.",
    spiegazione_es: "10 / 2 calcula la división de punto flotante y devuelve 5.0.",
  },
  {
    id: "bas-10",
    capitolo: 2,
    argomento: "Commento",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "# commento\nprint('OK')",
    risposte: ["OK", "# commento", "Niente", "Error"],
    indice_corretto: 0,
    suggerimento: "I commenti con # vengono ignorati dall'interprete.",
    spiegazione: "L'interprete ignora la riga del commento ed esegue solo print('OK').",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["OK", "# commento", "Nothing", "Error"],
    risposte_es: ["OK", "# commento", "Nada", "Error"],
    suggerimento_en: "Comments starting with # are ignored by the interpreter.",
    suggerimento_es: "Los comentarios con # son ignorados por el intérprete.",
    spiegazione_en: "The interpreter ignores the comment line and only executes print('OK').",
    spiegazione_es: "El intérprete ignora la línea del comentario y solo ejecuta print('OK').",
  },
  {
    id: "bas-11",
    capitolo: 1,
    argomento: "Booleano",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(True)",
    risposte: ["True", "1", "False", "Error"],
    indice_corretto: 0,
    suggerimento: "True si scrive con la T maiuscola.",
    spiegazione: "True è il valore booleano vero.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["True", "1", "False", "Error"],
    risposte_es: ["True", "1", "False", "Error"],
    suggerimento_en: "True is written with a capital T.",
    suggerimento_es: "True se escribe con la T mayúscula.",
    spiegazione_en: "True is the boolean value for true.",
    spiegazione_es: "True es el valor booleano verdadero.",
  },
  {
    id: "bas-12",
    capitolo: 1,
    argomento: "None",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(None)",
    risposte: ["None", "null", "vuoto", "Error"],
    indice_corretto: 0,
    suggerimento: "None rappresenta l'assenza di valore.",
    spiegazione: "None è un tipo speciale in Python usati per rappresentare il valore nullo.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["None", "null", "empty", "Error"],
    risposte_es: ["None", "null", "vacío", "Error"],
    suggerimento_en: "None represents the absence of a value.",
    suggerimento_es: "None representa la ausencia de valor.",
    spiegazione_en: "None is a special type in Python used to represent a null value.",
    spiegazione_es: "None es un tipo especial en Python utilizado para representar el valor nulo.",
  },
  {
    id: "bas-13",
    capitolo: 2,
    argomento: "Assegnazione",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "a = 1\na = 2\nprint(a)",
    risposte: ["2", "1", "Error", "Niente"],
    indice_corretto: 0,
    suggerimento: "La seconda assegnazione sovrascrive la prima.",
    spiegazione: "a riceve prima 1, poi viene riassegnata a 2.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["2", "1", "Error", "Nothing"],
    risposte_es: ["2", "1", "Error", "Nada"],
    suggerimento_en: "The second assignment overwrites the first.",
    suggerimento_es: "La segunda asignación sobrescribe la primera.",
    spiegazione_en: "a is first assigned 1, then it is reassigned to 2.",
    spiegazione_es: "a recibe primero 1, luego se reasigna a 2.",
  },
  {
    id: "bas-14",
    capitolo: 2,
    argomento: "Print multiplo",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "print(1, 2)",
    risposte: ["1 2", "1,2", "12", "Error"],
    indice_corretto: 0,
    suggerimento: "I valori passati a print() vengono separati da uno spazio.",
    spiegazione: "print separa gli argomenti con uno spazio di default.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["1 2", "1,2", "12", "Error"],
    risposte_es: ["1 2", "1,2", "12", "Error"],
    suggerimento_en: "Values passed to print() are separated by a space.",
    suggerimento_es: "Los valores pasados a print() se separan por un espacio.",
    spiegazione_en: "print separates arguments with a space by default.",
    spiegazione_es: "print separa los argumentos con un espacio por defecto.",
  },

  // --- FUNZIONI E CONDIZIONI (Capitoli 3-5) ---
  {
    id: "funz_01",
    capitolo: 3,
    argomento: "Funzioni base",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "def saluta():\n    print('Ciao')\n\nsaluta()",
    risposte: ["Ciao", "Niente", "Errore", "None"],
    indice_corretto: 0,
    suggerimento: "Chiamare una funzione esegue il suo blocco di codice.",
    spiegazione: "Definire la funzione la dichiara, ma chiamarla con saluta() esegue print('Ciao').",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Ciao", "Nothing", "Error", "None"],
    risposte_es: ["Ciao", "Nada", "Error", "None"],
    suggerimento_en: "Calling a function executes its code block.",
    suggerimento_es: "Llamar a una función ejecuta su bloque de código.",
    spiegazione_en: "Defining the function declares it, but calling it with saluta() executes print('Ciao').",
    spiegazione_es: "Definir la función la declara, pero llamarla con saluta() ejecuta print('Ciao').",
  },
  {
    id: "funz_02",
    capitolo: 3,
    argomento: "Parametri",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "def saluta(nome):\n    print('Ciao', nome)\n\nsaluta('Mario')",
    risposte: ["Ciao Mario", "Ciao nome", "Errore"],
    indice_corretto: 0,
    suggerimento: "Il parametro nome riceve la stringa 'Mario'.",
    spiegazione: "Il valore 'Mario' viene assegnato al parametro nome all'interno di saluta().",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Ciao Mario", "Ciao nome", "Error"],
    risposte_es: ["Ciao Mario", "Ciao nome", "Errore"],
    suggerimento_en: "The parameter nome receives the string 'Mario'.",
    suggerimento_es: "El parámetro nome recibe la cadena 'Mario'.",
    spiegazione_en: "The value 'Mario' is assigned to the parameter nome inside saluta().",
    spiegazione_es: "El valor 'Mario' se asigna al parámetro nome dentro de saluta().",
  },
  {
    id: "funz_03",
    capitolo: 3,
    argomento: "Return",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "def somma(a, b):\n    return a + b\n\nprint(somma(2, 3))",
    risposte: ["5", "Niente", "Errore"],
    indice_corretto: 0,
    suggerimento: "return restituisce il valore calcolato all'esterno.",
    spiegazione: "La funzione somma(2, 3) restituisce 5, che viene poi stampato.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["5", "Nothing", "Error"],
    risposte_es: ["5", "Niente", "Errore"],
    suggerimento_en: "return passes the calculated value to the outside.",
    suggerimento_es: "return devuelve el valor calculado al exterior.",
    spiegazione_en: "The function somma(2, 3) returns 5, which is then printed.",
    spiegazione_es: "La función somma(2, 3) devuelve 5, que luego se imprime.",
  },
  {
    id: "funz_04",
    capitolo: 3,
    argomento: "Funzioni vuote",
    difficolta: "facile",
    domanda: "Cosa restituisce questa funzione?",
    codice: "def stampa_e_torna():\n    print('Ciao')\n\nrisultato = stampa_e_torna()\nprint(risultato)",
    risposte: ["None", "Ciao", "Errore"],
    indice_corretto: 0,
    suggerimento: "Le funzioni senza un istruzione return esplicita restituiscono None.",
    spiegazione: "In Python, se non c'è un return esplicito, la funzione restituisce automaticamente None.",
    domanda_en: "What does this function return?",
    domanda_es: "¿Qué devuelve esta función?",
    risposte_en: ["None", "Ciao", "Error"],
    risposte_es: ["None", "Ciao", "Errore"],
    suggerimento_en: "Functions without an explicit return statement return None.",
    suggerimento_es: "Las funciones sin una instrucción return explícita devuelven None.",
    spiegazione_en: "In Python, if there is no explicit return, the function automatically returns None.",
    spiegazione_es: "En Python, si no hay un return explícito, la función devuelve automáticamente None.",
  },
  {
    id: "cond-01",
    capitolo: 5,
    argomento: "If vero",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "if True:\n    print('Sì')",
    risposte: ["Sì", "Niente", "True", "Error"],
    indice_corretto: 0,
    suggerimento: "La condizione è sempre True.",
    spiegazione: "Se la condizione è True, il blocco indentato dell'if viene eseguito.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Sì", "Nothing", "True", "Error"],
    risposte_es: ["Sì", "Niente", "True", "Error"],
    suggerimento_en: "The condition is always True.",
    suggerimento_es: "La condición es siempre True.",
    spiegazione_en: "If the condition is True, the indented block of the if statement is executed.",
    spiegazione_es: "Si la condición es True, se ejecuta el bloque indentado del if.",
  },
  {
    id: "funz_06",
    capitolo: 3,
    argomento: "Precedenza operatori in funzioni",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "def calcola(x, y, z):\n    return x + y * z\n\nprint(calcola(2, 3, 4))",
    risposte: ["14", "20", "24"],
    indice_corretto: 0,
    suggerimento: "Ricorda la precedenza della moltiplicazione sulla somma.",
    spiegazione: "3 * 4 fa 12, e 2 + 12 fa 14.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["14", "20", "24"],
    risposte_es: ["14", "20", "24"],
    suggerimento_en: "Remember the precedence of multiplication over addition.",
    suggerimento_es: "Recuerda la precedencia de la multiplicación sobre la suma.",
    spiegazione_en: "3 * 4 equals 12, and 2 + 12 equals 14.",
    spiegazione_es: "3 * 4 es 12, y 2 + 12 es 14.",
  },
  {
    id: "funz_07",
    capitolo: 3,
    argomento: "Scope delle variabili",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "x = 10\n\ndef modifica():\n    x = 5\n    print(x, end=' ')\n\nmodifica()\nprint(x)",
    risposte: ["5 10", "5 5", "10 10"],
    indice_corretto: 0,
    suggerimento: "La variabile x dentro la funzione è una variabile locale.",
    spiegazione: "x dentro modifica() è locale e non sovrascrive la x globale. Stampa prima 5 e poi 10.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["5 10", "5 5", "10 10"],
    risposte_es: ["5 10", "5 5", "10 10"],
    suggerimento_en: "The variable x inside the function is a local variable.",
    suggerimento_es: "La variable x dentro de la función es una variable local.",
    spiegazione_en: "x inside modifica() is local and does not overwrite the global x. It prints 5 first and then 10.",
    spiegazione_es: "x dentro de modifica() es local y no sobrescribe la x global. Imprime primero 5 y luego 10.",
  },
  {
    id: "funz_08",
    capitolo: 3,
    argomento: "Return multiplo (Tupla)",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "def coord():\n    return 10, 20\n\nx, y = coord()\nprint(x + y)",
    risposte: ["30", "10, 20", "Errore"],
    indice_corretto: 0,
    suggerimento: "Return 10, 20 restituisce una tupla scompattata in x e y.",
    spiegazione: "coord() restituisce (10, 20), x diventa 10 e y 20, quindi x + y = 30.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["30", "10, 20", "Error"],
    risposte_es: ["30", "10, 20", "Error"],
    suggerimento_en: "Return 10, 20 returns a tuple unpacked into x and y.",
    suggerimento_es: "Return 10, 20 devuelve una tupla desempaquetada en x e y.",
    spiegazione_en: "coord() returns (10, 20), x becomes 10 and y becomes 20, therefore x + y = 30.",
    spiegazione_es: "coord() devuelve (10, 20), x se convierte en 10 e y en 20, por lo tanto x + y = 30.",
  },
  {
    id: "cond-05",
    capitolo: 5,
    argomento: "Elif",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "x = 5\nif x > 10:\n    print('A')\nelif x > 3:\n    print('B')\nelse:\n    print('C')",
    risposte: ["B", "A", "C", "Niente"],
    indice_corretto: 0,
    suggerimento: "Valuta le condizioni in ordine sequenziale.",
    spiegazione: "5 non è > 10, ma 5 > 3 è True, quindi stampa 'B'.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["B", "A", "C", "Nothing"],
    risposte_es: ["B", "A", "C", "Nada"],
    suggerimento_en: "Evaluate the conditions in sequential order.",
    suggerimento_es: "Evalúa las condiciones en orden secuencial.",
    spiegazione_en: "5 is not > 10, but 5 > 3 is True, so it prints 'B'.",
    spiegazione_es: "5 no es > 10, pero 5 > 3 es True, por lo tanto imprime 'B'.",
  },
  {
    id: "cond-06",
    capitolo: 5,
    argomento: "Operatori logici",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "a = True\nb = False\nprint(a and b, a or b)",
    risposte: ["False True", "True False", "True True", "False False"],
    indice_corretto: 0,
    suggerimento: "and richiede entrambi True; or richiede che almeno uno sia True.",
    spiegazione: "True and False è False, mentre True or False è True.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["False True", "True False", "True True", "False False"],
    risposte_es: ["False True", "True False", "True True", "False False"],
    suggerimento_en: "and requires both to be True; or requires at least one to be True.",
    suggerimento_es: "and requiere que ambos sean True; or requiere que al menos uno sea True.",
    spiegazione_en: "True and False is False, while True or False is True.",
    spiegazione_es: "True and False es False, mientras que True or False es True.",
  },

  // --- CICLI E STRINGHE (Capitoli 7-8) ---
  {
    id: "cicli_01",
    capitolo: 7,
    argomento: "Ciclo while",
    difficolta: "facile",
    domanda: "Quante volte viene stampato 'Ciao'?",
    codice: "i = 0\nwhile i < 3:\n    print('Ciao')\n    i += 1",
    risposte: ["3", "2", "4"],
    indice_corretto: 0,
    suggerimento: "i assume i valori 0, 1 e 2.",
    spiegazione: "Il ciclo itera con i=0, i=1 e i=2, quindi esattamente 3 volte.",
    domanda_en: "How many times is 'Ciao' printed?",
    domanda_es: "¿Cuántas veces se imprime 'Ciao'?",
    risposte_en: ["3", "2", "4"],
    risposte_es: ["3", "2", "4"],
    suggerimento_en: "i takes the values 0, 1, and 2.",
    suggerimento_es: "i toma los valores 0, 1 y 2.",
    spiegazione_en: "The loop iterates with i=0, i=1, and i=2, therefore exactly 3 times.",
    spiegazione_es: "El ciclo itera con i=0, i=1 e i=2, por lo tanto exactamente 3 veces.",
  },
  {
    id: "cicli_02",
    capitolo: 7,
    argomento: "For con range",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "for i in range(3):\n    print(i, end=' ')",
    risposte: ["0 1 2", "1 2 3", "0 1 2 3"],
    indice_corretto: 0,
    suggerimento: "range(3) genera numeri da 0 fino a 2 (escluso il 3).",
    spiegazione: "range(3) produce i valori 0, 1, 2.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["0 1 2", "1 2 3", "0 1 2 3"],
    risposte_es: ["0 1 2", "1 2 3", "0 1 2 3"],
    suggerimento_en: "range(3) generates numbers from 0 up to 2 (excluding 3).",
    suggerimento_es: "range(3) genera números desde 0 hasta 2 (excluyendo el 3).",
    spiegazione_en: "range(3) produces the values 0, 1, 2.",
    spiegazione_es: "range(3) produce los valores 0, 1, 2.",
  },
  {
    id: "cicli_04",
    capitolo: 7,
    argomento: "Break nei cicli",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "for i in range(5):\n    if i == 2:\n        break\n    print(i, end=' ')",
    risposte: ["0 1", "0 1 2", "0 1 2 3 4"],
    indice_corretto: 0,
    suggerimento: "break interrompe immediatamente l'esecuzione del ciclo.",
    spiegazione: "Quando i vale 2, la condizione i==2 scatta ed esegue break, interrompendo il ciclo.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["0 1", "0 1 2", "0 1 2 3 4"],
    risposte_es: ["0 1", "0 1 2", "0 1 2 3 4"],
    suggerimento_en: "break immediately stops the execution of the loop.",
    suggerimento_es: "break interrumpe inmediatamente la ejecución del ciclo.",
    spiegazione_en: "When i equals 2, the condition i==2 is met and executes break, terminating the loop.",
    spiegazione_es: "Cuando i vale 2, la condición i==2 se cumple y ejecuta break, interrumpiendo el ciclo.",
  },
  {
    id: "str_01",
    capitolo: 8,
    argomento: "Lunghezza stringa",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "print(len('Python'))",
    risposte: ["6", "5", "7"],
    indice_corretto: 0,
    suggerimento: "len() conta il numero di caratteri.",
    spiegazione: "La parola 'Python' è composta da 6 caratteri.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["6", "5", "7"],
    risposte_es: ["6", "5", "7"],
    suggerimento_en: "len() counts the number of characters.",
    suggerimento_es: "len() cuenta el número de caracteres.",
    spiegazione_en: "The word 'Python' consists of 6 characters.",
    spiegazione_es: "La palabra 'Python' está compuesta por 6 caracteres.",
  },
  {
    id: "str_02",
    capitolo: 8,
    argomento: "Indice e Slicing",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "s = 'Python'\nprint(s[1:4])",
    risposte: ["yth", "Pyt", "ytho"],
    indice_corretto: 0,
    suggerimento: "s[1:4] prende i caratteri dall'indice 1 all'indice 3.",
    spiegazione: "In 'Python', indice 1 è 'y', 2 è 't', 3 è 'h'. L'indice finale 4 è escluso.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["yth", "Pyt", "ytho"],
    risposte_es: ["yth", "Pyt", "ytho"],
    suggerimento_en: "s[1:4] takes characters from index 1 to index 3.",
    suggerimento_es: "s[1:4] toma los caracteres desde el índice 1 hasta el índice 3.",
    spiegazione_en: "In 'Python', index 1 is 'y', 2 is 't', 3 is 'h'. The end index 4 is excluded.",
    spiegazione_es: "En 'Python', el índice 1 es 'y', el 2 es 't', el 3 es 'h'. El índice final 4 está excluido.",
  },
  {
    id: "str_03",
    capitolo: 8,
    argomento: "Immutabilità delle stringhe",
    difficolta: "difficile",
    domanda: "Cosa succede eseguendo questo codice?",
    codice: "s = 'Python'\ns[0] = 'p'",
    risposte: ["Errore TypeError", "s diventa 'python'", "Niente, funziona"],
    indice_corretto: 0,
    suggerimento: "Le stringhe in Python non sono modificabili in-place.",
    spiegazione: "Le stringhe sono immutabili in Python, quindi assegnare a un indice genera un TypeError.",
    domanda_en: "What happens when running this code?",
    domanda_es: "¿Qué sucede al ejecutar este código?",
    risposte_en: ["TypeError", "s becomes 'python'", "Nothing, it works"],
    risposte_es: ["Error TypeError", "s se convierte en 'python'", "Nada, funciona"],
    suggerimento_en: "Strings in Python are not mutable in-place.",
    suggerimento_es: "Las cadenas en Python no son modificables in-place.",
    spiegazione_en: "Strings are immutable in Python, so assigning to an index raises a TypeError.",
    spiegazione_es: "Las cadenas son inmutables en Python, por lo que asignar un valor a un índice genera un TypeError.",
  },

  // --- LISTE, DIZIONARI, TUPLE (Capitoli 10-12) ---
  {
    id: "liste_02",
    capitolo: 10,
    argomento: "Indice liste",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "numeri = [10, 20, 30]\nprint(numeri[1])",
    risposte: ["20", "10", "30"],
    indice_corretto: 0,
    suggerimento: "Gli indici delle liste partono da 0.",
    spiegazione: "numeri[0] è 10, numeri[1] è 20.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["20", "10", "30"],
    risposte_es: ["20", "10", "30"],
    suggerimento_en: "List indices start at 0.",
    suggerimento_es: "Los índices de las listas comienzan en 0.",
    spiegazione_en: "numeri[0] is 10, numeri[1] is 20.",
    spiegazione_es: "numeri[0] es 10, numeri[1] es 20.",
  },
  {
    id: "liste_04",
    capitolo: 10,
    argomento: "Metodo append",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "numeri = [1, 2]\nnumeri.append(3)\nprint(numeri)",
    risposte: ["[1, 2, 3]", "[1, 2]", "[3]"],
    indice_corretto: 0,
    suggerimento: "append aggiunge un elemento in coda alla lista.",
    spiegazione: "append(3) modifica la lista aggiungendo 3 alla fine.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["[1, 2, 3]", "[1, 2]", "[3]"],
    risposte_es: ["[1, 2, 3]", "[1, 2]", "[3]"],
    suggerimento_en: "append adds an element to the end of the list.",
    suggerimento_es: "append añade un elemento al final de la lista.",
    spiegazione_en: "append(3) modifies the list by adding 3 to the end.",
    spiegazione_es: "append(3) modifica la lista añadiendo 3 al final.",
  },
  {
    id: "liste_11",
    capitolo: 10,
    argomento: "Riferimenti e copie",
    difficolta: "difficile",
    domanda: "Cosa stampa questo codice?",
    codice: "a = [1, 2]\nb = a\nb.append(3)\nprint(a)",
    risposte: ["[1, 2, 3]", "[1, 2]", "Errore"],
    indice_corretto: 0,
    suggerimento: "L'assegnazione b = a copia il riferimento all'oggetto, non la lista.",
    spiegazione: "Sia a che b puntano alla stessa lista in memoria. Modificando b si modifica a.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["[1, 2, 3]", "[1, 2]", "Error"],
    risposte_es: ["[1, 2, 3]", "[1, 2]", "Error"],
    suggerimento_en: "The assignment b = a copies the reference to the object, not the list.",
    suggerimento_es: "La asignación b = a copia la referencia al objeto, no la lista.",
    spiegazione_en: "Both a and b point to the same list in memory. Modifying b also modifies a.",
    spiegazione_es: "Tanto a como b apuntan a la misma lista en memoria. Al modificar b, se modifica a.",
  },
  {
    id: "diz_01",
    capitolo: 11,
    argomento: "Dizionari",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "persona = {'nome': 'Anna', 'eta': 25}\nprint(persona['nome'])",
    risposte: ["Anna", "nome", "25", "KeyError"],
    indice_corretto: 0,
    suggerimento: "L'accesso avviene tramite chiave tra parentesi quadre.",
    spiegazione: "persona['nome'] restituisce il valore associato alla chiave 'nome', ovvero 'Anna'.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Anna", "nome", "25", "KeyError"],
    risposte_es: ["Anna", "nome", "25", "KeyError"],
    suggerimento_en: "Access is performed using the key inside square brackets.",
    suggerimento_es: "El acceso se realiza mediante la clave entre corchetes.",
    spiegazione_en: "persona['nome'] returns the value associated with the key 'nome', which is 'Anna'.",
    spiegazione_es: "persona['nome'] devuelve el valor asociado a la clave 'nome', es decir, 'Anna'.",
  },
  {
    id: "diz_02",
    capitolo: 11,
    argomento: "Metodo get",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "diz = {'a': 1, 'b': 2}\nprint(diz.get('c', 0))",
    risposte: ["0", "None", "KeyError", "c"],
    indice_corretto: 0,
    suggerimento: "get(chiave, default) restituisce default se la chiave non esiste.",
    spiegazione: "La chiave 'c' non esiste nel dizionario, quindi get() restituisce il fallback 0.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["0", "None", "KeyError", "c"],
    risposte_es: ["0", "None", "KeyError", "c"],
    suggerimento_en: "get(key, default) returns default if the key does not exist.",
    suggerimento_es: "get(chiave, default) devuelve default si la clave no existe.",
    spiegazione_en: "The key 'c' does not exist in the dictionary, so get() returns the fallback 0.",
    spiegazione_es: "La clave 'c' no existe en el diccionario, por lo tanto get() devuelve el valor por defecto 0.",
  },
  {
    id: "tupla_01",
    capitolo: 12,
    argomento: "Immutabilità della tupla",
    difficolta: "difficile",
    domanda: "Cosa succede eseguendo questo codice?",
    codice: "t = (1, 2, 3)\nt[0] = 99",
    risposte: ["Errore TypeError", "t diventa (99, 2, 3)", "Niente, funziona"],
    indice_corretto: 0,
    suggerimento: "Le tuple sono sequenze immutabili.",
    spiegazione: "In Python le tuple non si possono modificare dopo la loro creazione.",
    domanda_en: "What happens when running this code?",
    domanda_es: "¿Qué sucede al ejecutar este código?",
    risposte_en: ["TypeError error", "t becomes (99, 2, 3)", "Nothing, it works"],
    risposte_es: ["Error TypeError", "t se convierte en (99, 2, 3)", "Nada, funciona"],
    suggerimento_en: "Tuples are immutable sequences.",
    suggerimento_es: "Las tuplas son secuencias inmutables.",
    spiegazione_en: "In Python, tuples cannot be modified after they are created.",
    spiegazione_es: "En Python, las tuplas no se pueden modificar después de su creación.",
  },

  // --- CLASSI, OGGETTI ED ERRORI (Capitoli 14-17) ---
  {
    id: "classi_03",
    capitolo: 15,
    argomento: "Metodo __init__",
    difficolta: "facile",
    domanda: "Cosa stampa questo codice?",
    codice: "class Saluto:\n    def __init__(self, nome):\n        self.nome = nome\n\ns = Saluto('Mario')\nprint(s.nome)",
    risposte: ["Mario", "Saluto", "Errore"],
    indice_corretto: 0,
    suggerimento: "__init__ è il costruttore della classe.",
    spiegazione: "__init__ assegna 'Mario' all'attributo self.nome dell'istanza s.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Mario", "Saluto", "Errore"],
    risposte_es: ["Mario", "Saluto", "Errore"],
    suggerimento_en: "__init__ is the class constructor.",
    suggerimento_es: "__init__ es el constructor de la clase.",
    spiegazione_en: "__init__ assigns 'Mario' to the self.nome attribute of the instance s.",
    spiegazione_es: "__init__ asigna 'Mario' al atributo self.nome de la instancia s.",
  },
  {
    id: "classi_06",
    capitolo: 16,
    argomento: "Ereditarietà",
    difficolta: "media",
    domanda: "Cosa stampa questo codice?",
    codice: "class Animale:\n    def verso(self):\n        return '...'\n\nclass Cane(Animale):\n    def verso(self):\n        return 'Bau!'\n\nc = Cane()\nprint(c.verso())",
    risposte: ["Bau!", "...", "Errore"],
    indice_corretto: 0,
    suggerimento: "Cane eredita da Animale e ridefinisce verso().",
    spiegazione: "La classe figlia Cane sovrascrive il metodo verso() del genitore.",
    domanda_en: "What does this code print?",
    domanda_es: "¿Qué imprime este código?",
    risposte_en: ["Bau!", "...", "Errore"],
    risposte_es: ["Bau!", "...", "Errore"],
    suggerimento_en: "Cane inherits from Animale and redefines verso().",
    suggerimento_es: "Cane hereda de Animale y redefine verso().",
    spiegazione_en: "The child class Cane overrides the verso() method of the parent.",
    spiegazione_es: "La clase hija Cane sobrescribe el método verso() del padre.",
  },
  {
    id: "errori_01",
    capitolo: 1,
    argomento: "SyntaxError",
    difficolta: "difficile",
    domanda: "Che errore produce questo codice?",
    codice: "if True\n    print('Ciao')",
    risposte: ["SyntaxError", "NameError", "IndentationError"],
    indice_corretto: 0,
    suggerimento: "Osserva la mancanza dei due punti dopo l'if.",
    spiegazione: "In Python le istruzioni condizionali richiedono i due punti (:) prima del blocco.",
    domanda_en: "What error does this code produce?",
    domanda_es: "¿Qué error produce este código?",
    risposte_en: ["SyntaxError", "NameError", "IndentationError"],
    risposte_es: ["SyntaxError", "NameError", "IndentationError"],
    suggerimento_en: "Observe the missing colon after the if statement.",
    suggerimento_es: "Observa la falta de los dos puntos después del if.",
    spiegazione_en: "In Python, conditional statements require a colon (:) before the block.",
    spiegazione_es: "En Python, las instrucciones condicionales requieren dos puntos (:) antes del bloque.",
  },
  {
    id: "errori_06",
    capitolo: 1,
    argomento: "ZeroDivisionError",
    difficolta: "difficile",
    domanda: "Che errore produce questo codice?",
    codice: "10 / 0",
    risposte: ["ZeroDivisionError", "ValueError", "TypeError"],
    indice_corretto: 0,
    suggerimento: "Dividere per zero non è consentito in matematica né in Python.",
    spiegazione: "La divisione per zero solleva l'eccezione ZeroDivisionError.",
    domanda_en: "What error does this code produce?",
    domanda_es: "¿Qué error produce este código?",
    risposte_en: ["ZeroDivisionError", "ValueError", "TypeError"],
    risposte_es: ["ZeroDivisionError", "ValueError", "TypeError"],
    suggerimento_en: "Dividing by zero is not allowed in mathematics or in Python.",
    suggerimento_es: "Dividir por cero no está permitido ni en matemáticas ni en Python.",
    spiegazione_en: "Division by zero raises the ZeroDivisionError exception.",
    spiegazione_es: "La división por cero lanza la excepción ZeroDivisionError.",
  },
  {
    id: "errori_07",
    capitolo: 1,
    argomento: "AttributeError",
    difficolta: "difficile",
    domanda: "Che errore produce questo codice?",
    codice: "'ciao'.uppercase()",
    risposte: ["AttributeError", "NameError", "TypeError"],
    indice_corretto: 0,
    suggerimento: "Il metodo delle stringhe in Python si chiama upper(), non uppercase().",
    spiegazione: "Invocare un metodo o attributo inesistente genera un AttributeError.",
    domanda_en: "What error does this code produce?",
    domanda_es: "¿Qué error produce este código?",
    risposte_en: ["AttributeError", "NameError", "TypeError"],
    risposte_es: ["AttributeError", "NameError", "TypeError"],
    suggerimento_en: "The string method in Python is called upper(), not uppercase().",
    suggerimento_es: "El método de cadenas en Python se llama upper(), no uppercase().",
    spiegazione_en: "Invoking a non-existent method or attribute generates an AttributeError.",
    spiegazione_es: "Invocar un método o atributo inexistente genera un AttributeError.",
  }
].map((s: any) => normalizeChallenge({ ...s, trackId: s.trackId || 'python' }));

// Backward compatibility export
export const TUTTE_LE_SFIDE: Sfida[] = SFIDE_PYTHON;

export function getQuestionsForTrack(trackId: TrackId): Sfida[] {
  let list: Sfida[] = [];
  switch (trackId) {
    case 'typescript':
      list = INITIAL_TYPESCRIPT_CHALLENGES;
      break;
    case 'git':
      list = INITIAL_GIT_CHALLENGES;
      break;
    case 'docker':
      list = DOCKER_CHALLENGES;
      break;
    case 'postgres':
      list = POSTGRES_CHALLENGES;
      break;
    case 'prompt_engineering':
      list = AI_NATIVE_CHALLENGES.filter(q => q.trackId === 'prompt_engineering');
      break;
    case 'mcp':
      list = AI_NATIVE_CHALLENGES.filter(q => q.trackId === 'mcp');
      break;
    case 'claude_code':
      list = AI_NATIVE_CHALLENGES.filter(q => q.trackId === 'claude_code');
      break;
    case 'python':
    default:
      list = SFIDE_PYTHON;
      break;
  }
  return list.map((q) => normalizeChallenge(q));
}

export function getAllQuestions(): Sfida[] {
  return [
    ...SFIDE_PYTHON, 
    ...INITIAL_TYPESCRIPT_CHALLENGES, 
    ...INITIAL_GIT_CHALLENGES,
    ...DOCKER_CHALLENGES,
    ...POSTGRES_CHALLENGES,
    ...AI_NATIVE_CHALLENGES
  ].map((q) => normalizeChallenge(q));
}


