name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint & Type Check
    runs-on: [self-hosted, soliso, devquest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Type Check & Build
        run: |
          npm install --no-audit --no-fund
          npx tsc --noEmit
          npm run build
