name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint & Type Check
    runs-on: [self-hosted, soliso, devquest]

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4 pin SHA

      - name: Type Check & Build
        run: |
          bun install --frozen-lockfile
          bunx tsc --noEmit
          bun run build
